apiVersion: v1
kind: Pod
metadata:
  name: task-mysql-server
  labels: 
    app: task-mysql-server
spec:
  containers:
    - name: task-mysql-server
      image: mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: task-mysql-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: task-mysql-config
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: task-mysql-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: task-mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: task-mysql-secret
              key: MYSQL_ROOT_PASSWORD
      volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
        

---
apiVersion: v1
kind: Service
metadata:
  name: task-mysql-service
spec:
  selector:
    app: task-mysql-server
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
