version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deploy_scripts/validate.sh
      timeout: 60
      runas: ec2-user
